<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>Friendwindow</name>
    <message>
        <source>Friend List</source>
        <translation>好友列表</translation>
    </message>
    <message>
        <source>Friends</source>
        <translation>好友</translation>
    </message>
</context>
<context>
    <name>Profilewindow</name>
    <message>
        <source>Profile</source>
        <translation>个人资料</translation>
    </message>
    <message>
        <source>Back</source>
        <translation>返回</translation>
    </message>
    <message>
        <source>No bio</source>
        <translation>暂无简介</translation>
    </message>
</context>
<context>
    <name>ChatWindow</name>
    <message>
        <source>Chat</source>
        <translation>聊天</translation>
    </message>
    <message>
        <source>Message</source>
        <translation>消息</translation>
    </message>
    <message>
        <source>Send</source>
        <translation>发送</translation>
    </message>
    <message>
        <source>Tap to open chat</source>
        <translation>点击开始聊天</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Home</source>
        <translation>首页</translation>
    </message>
    <message>
        <source>Friends</source>
        <translation>好友</translation>
    </message>
    <message>
        <source>Post</source>
        <translation>发布</translation>
    </message>
    <message>
        <source>Chat</source>
        <translation>聊天</translation>
    </message>
    <message>
        <source>Profile</source>
        <translation>资料</translation>
    </message>
    <message>
        <source>Search friends...</source>
        <translation>搜索好友...</translation>
    </message>
    <message>
        <source>Suggested</source>
        <translation>推荐</translation>
    </message>
    <message>
        <source>Add comment...</source>
        <translation>添加评论...</translation>
    </message>
    <message>
        <source>Share Profile</source>
        <translation>分享资料</translation>
    </message>
    <message>
        <source>Posts are private by default</source>
        <translation>帖子默认设为私密</translation>
    </message>
    <message>
        <source>Video</source>
        <translation>视频</translation>
    </message>
    <message>
        <source>Comments</source>
        <translation>评论</translation>
    </message>
    <message>
        <source>Copy Link</source>
        <translation>复制链接</translation>
    </message>
    <message>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <source>Close</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>Share</source>
        <translation>分享</translation>
    </message>
    <message>
        <source>Follow</source>
        <translation>关注</translation>
    </message>
    <message>
        <source>Followed</source>
        <translation>已关注</translation>
    </message>
</context>
</TS>
